### PR TITLE
New initialization methods

### PR DESCRIPTION
**Pull request by victorg1991**
I have added some initialization options:
- You can specify the storyboard name where the VCs are
- You can specify the storyboard object to instanciate the VCs through it
- You can initialize the swift pages with an array of VC instead of an array of VCs identifier

### CODE REVIEW

**Comment by andres-ciano-umewin** [comment]
👍 would be great to being able to use custom storyboards other than "Main"

**Comment by GabrielAlva** [comment]
Hi, 
Victor sorry for the late response, thanks for your pull request, I'll check it this weekend!

**Comment by GabrielAlva** [comment]
Andres, you could use it on another storyboard or on an XIB file

**Comment by victorg1991** [comment]
Thanks Gabriel,

I hope you like it 😀

**Comment by andres-ciano-umewin** [comment]
@GabrielAlva Yeah, I tried, but the module always loads the VCs from "Main"... That's why I found this PR to be a great addition ;)

Something I missed?

**Pull request merged**
