### PR TITLE
fixed infinite x of animated bar at the first time to draw rect

### PR DESCRIPTION
**Pull request by wjiuxing**
fixed infinite x of animated bar at the first time to draw rect

### CODE REVIEW

**Comment by GabrielAlva** [comment]
Hi, 
Thank you for your contribution :)

**Comment by wjiuxing** [comment]
I have to apologize for that x issue was caused by my typo and  has been merged before. Thanks. :)

**Comment by GabrielAlva** [comment]
No problem :) right now Im debugging the bug where the content disappears, Ive got a pretty good idea why it happened and how to fix it. The only thing Im trying to do is see if I can get a consistent behaviour on when the content disappears before I apply the fix, but its intermittent. If you know how to recreate that scenario let me know :)

**Comment by wjiuxing** [comment]
I am not sure I understand your bug. I find a crasher on an nil currentPage value when rotate the device.

**Comment by GabrielAlva** [comment]
I solved that issue along with the one I was talking about. I just pushed, please check it out :)

**Comment by wjiuxing** [comment]
I find this bug is still exist. I would file this issue soon and let's talk it in a new thread (see [App crashed when the first orientation change is to rotate to "Upside Down"](https://github.com/GabrielAlva/SwiftPages/issues/26)). Thanks.

**Pull request merged**
